import React from 'react';
export const HorasContext = React.createContext(
    {H7: {},
    H8: {},
    H9: {},
    H10: {},
    H11: {},
    H12: {},
    H13: {},
    H14: {},
    H15: {},
    H16: {},
    H17: {},
    H18: {},
    H19: {},
    H20: {},
    H21: {},
    H22: {},
    HorasChanger: () => {},
    });