
// Temas específicos dispuestos
export const themesOptions = [
    { value: 'chocolate', label: 'Chocolate' },
    { value: 'Cálculo diferencial', label: 'Cálculo diferencial' },
    { value: 'Cálculo Integral', label: 'Cálculo Integral' },
    { value: 'Cálculo vectorial', label: 'Cálculo vectorial' },
    { value: 'Algebra lineal', label: 'Algebra lineal' },
    { value: 'Geometría', label: 'Geometría' },
    { value: 'Geometría analitica', label: 'Geometría analitica' },
    { value: 'ecuaciones diferenciales', label: 'ecuaciones diferenciales' },
    { value: 'matemáticas especiales', label: 'matemáticas especiales' },
    { value: 'matemáticas discretas', label: 'matemáticas discretas' },
    { value: 'matemática financiera', label: 'matemática financiera' },
    { value: 'matemática bachillerato', label: 'matemática bachillerato' },
    { value: 'Física mecánica', label: 'Física mecánica' },
    { value: 'Física moderna', label: 'Física moderna' },
    { value: 'Física de fluidos', label: 'Física de fluidos' },
    { value: 'Física térmica', label: 'Física térmica' },
    { value: 'Física ondas', label: 'Física ondas' },
    { value: 'Física electricidad y magnetismo', label: 'Física electricidad y magnetismo' },
    { value: 'Física electromagnética', label: 'Física electromagnética' },
    { value: 'Física estadística', label: 'Física estadística' },
    { value: 'Física bachillerato', label: 'Física bachillerato' },
    { value: 'Inglés nivel A1', label: 'Inglés nivel A1' },
    { value: 'Inglés nivel A2', label: 'Inglés nivel A2' },
    { value: 'Inglés nivel B1', label: 'Inglés nivel B1' },
    { value: 'Inglés nivel B2', label: 'Inglés nivel B2' },
    { value: 'Inglés nivel C1', label: 'Inglés nivel C1' },
    { value: 'Inglés nivel C2', label: 'Inglés nivel C2' },
    { value: 'Programación Web', label: 'Programación Web' },
    { value: 'Programación Móvil', label: 'Programación Móvil' },
    { value: 'POO', label: 'POO' },
    { value: 'Estructura de datos', label: 'Estructura de datos' },
    { value: 'Programación básica', label: 'Programación básica' },
    { value: 'Python', label: 'Python' },
    { value: 'C', label: 'C' },
    { value: 'Javascript', label: 'Javascript' },
    { value: 'Ingeniería Electrónica', label: 'Ingeniería Electrónica' },
    { value: 'Ingeniería de Sistemas', label: 'Ingeniería de Sistemas' },
    { value: 'Ingeniería Ambiental', label: 'Ingeniería Ambiental' },
    { value: 'Ingeniería Civil', label: 'Ingeniería Civil' },
    { value: 'Ingeniería Agronómica', label: 'Ingeniería Agronómica' },
    { value: 'Ingeniería Pesquera', label: 'Ingeniería Pesquera' },
    { value: 'Ingeniería Industrial', label: 'Ingeniería Industrial' },
];